### ISSUE TITLE
支持渡輪航班時間

### ISSUE THREAD

**Issue by kennyfong19931** [kennyfong19931/siri-shortcut-hk-bus-eta#8]
### Resources
只包括資料一線通有資料的航班

- [持牌渡輪服務詳情及收費表](https://data.gov.hk/tc-data/dataset/hk-td-wcms_8-ferry-services-tt-ft)
- [香港水上的士航班時間表及價目表](https://data.gov.hk/tc-data/dataset/ff-watertaxi-schedule1)
- [香港水上的士預計到達時間](https://data.gov.hk/tc-data/dataset/ff-watertaxi-schedule2)
- [天星小輪有限公司渡輪服務航班時間表及收費表](https://data.gov.hk/tc-data/dataset/starferry-starferry-ferry-service-timetables-and-fare-tables-of-star-ferry)
- [富裕小輪有限公司渡輪航班時間表及價目表](https://data.gov.hk/tc-data/dataset/ff-fortune-schedule1)
- [富裕小輪渡輪預計到達時間](https://data.gov.hk/tc-data/dataset/ff-fortune-schedule2)
- [港九小輪渡輪服務時間表、收費表及預計到達時間數據](https://data.gov.hk/tc-data/dataset/hkkf-hkkfdata-hkkf-eta-data)
- [新渡輪下一航班的預計抵達時間](https://data.gov.hk/tc-data/dataset/sunferry-eta-eta)
- [新渡輪服務有限公司渡輪服務航班時間表](https://data.gov.hk/tc-data/dataset/sunferry-timetables-timetables)
- [新渡輪服務有限公司渡輪服務收費表](https://data.gov.hk/tc-data/dataset/sunferry-faretables-faretables)
- [翠華船務(香港)有限公司渡輪服務航班時間表](https://data.gov.hk/tc-data/dataset/traway-tsuiwah-timetables)
- [翠華船務(香港)有限公司渡輪服務收費表](https://data.gov.hk/tc-data/dataset/traway-tsuiwah-faretable)
- [梅窩至愉景灣收費表](https://data.gov.hk/tc-data/dataset/pckt-pcktdata-peng-chau-kai-to-fare)
- [梅窩至愉景灣時間表](https://data.gov.hk/tc-data/dataset/pckt-pcktdata-peng-chau-kai-to-service-time)
- [香港仔至索罟灣經模達時間表](https://data.gov.hk/tc-data/dataset/ckf-team1-chuen-kee-ferry-service-time)
- [香港仔至索罟灣經模達票價表](https://data.gov.hk/tc-data/dataset/ckf-team1-chuen-kee-ferry-service-fare)
- [跨境渡輪服務抵港航班資料](https://data.gov.hk/tc-data/dataset/hk-md-mardep-crossboundaryferryservices-arrive)
- [跨境渡輪服務離港航班資料](https://data.gov.hk/tc-data/dataset/hk-md-mardep-crossboundaryferryservices-depart)

### Tasks
- [ ] [API] Add route stop crawler
- [ ] [API] Add eta
- [ ] [Siri Shortcut] Support route/pier selection
- [ ] [web] Support route/pier selection
